name: flutter_onboarding_widgets
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  #introduction_screen.dart
  introduction_screen: ^4.0.0

  #intro_slider_screens
  intro_slider: ^4.2.5

  #onboarding_slider_screen
  flutter_onboarding_slider: ^1.0.11

  #concentric_transition_xoxo
  concentric_transition: ^1.0.3

  #animated_introduction
  animated_introduction: ^1.0.4

  #gone_board
  gone_board: ^1.0.5

  #flutter_carousel_intro
  flutter_carousel_intro: ^1.0.11
  flutter_svg: ^2.2.3

  #animated_page_reveal
  animated_page_reveal: ^1.0.0
  google_fonts: ^6.3.2

  #onboarding_animation
  onboarding_animation: ^0.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 700